version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: senhasecreta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
